"""
Generate a synthetic 13-year listening history, so the pipeline can be run and
checked by someone who is not me.

WHY A SIMULATOR IS PART OF THE DELIVERABLE
------------------------------------------
This project's real input is one person's Spotify account. That input cannot be
committed to a repository, cannot be shared, and cannot be regenerated by a
reader — which would make every number in the write-up unverifiable and the
code untestable. So the pipeline ships with a listener it can invent: same
schema, same shapes, deterministic from a seed.

WHAT IS AND IS NOT REAL ABOUT IT
--------------------------------
The generative process below is a hypothesis about how listening works, not a
finding. It bakes in the effects the analysis then goes looking for, which
means **a good result on simulated data proves the code runs, not that the
theory holds.** The only claim made for the demo output is that the pipeline
executes end to end and the estimates recover the parameters written here.

What it does buy: the estimation code is exercised against data whose true
answer is known, so if `run_memory_lane.py` reports an effect the simulator
never put in, that is a bug and it is visible.

THE GENERATIVE STORY
--------------------
  * ~1,400 tracks enter the library across 2013-2026, at a rate that rises
    through the teens and settles in the twenties.
  * Each track belongs to one of six latent "sonic worlds" — correlated blobs
    in acoustic space. K-Means is supposed to find these; that is the check.
  * Each track has a private `affinity`, which is idiosyncratic and NOT a
    function of acoustics. This is the simulator's core assumption: what you
    love is mostly not predictable from what a song sounds like.
  * Plays arrive as a burst around the entry date, with a width that varies —
    some tracks are welded to one season, some are played evenly for years.
  * A track becomes a RETURNER (dormant a year or more, then played again)
    with probability driven MOSTLY by affinity and A LITTLE by arousal and
    emotional intensity. That 'a little' is the effect size the analysis is
    built to measure honestly:

        logit(returner) = -1.35 + 1.50·affinity + 0.35·arousal + 0.25·|valence-0.5|

    Behaviour proxies affinity well, so the analysis should find that acoustic
    features add real but small predictive value on top of behaviour. If the
    report claims a large acoustic effect, something is wrong.

Names are combinatorially generated and deliberately do not correspond to real
artists or recordings. Every row carries `simulated = True`.

Usage:  python memory-lane/simulate_listener.py [--seed 7] [--birth-year 2005]
Writes: memory-lane/data/{tracks,streams}.csv, memory-lane/data/source.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

DATA = Path(__file__).resolve().parent / "data"

START, END = pd.Timestamp("2013-01-01"), pd.Timestamp("2026-08-01")
N_TRACKS = 1400

# The six sonic worlds: (danceability, energy, valence, acousticness,
# speechiness, instrumentalness, tempo, loudness) centres.
WORLDS = {
    "bedroom acoustic":  (0.42, 0.28, 0.36, 0.82, 0.04, 0.12,  92, -13.5),
    "stadium indie":     (0.55, 0.78, 0.55, 0.11, 0.05, 0.02, 132,  -5.4),
    "late-night pop":    (0.74, 0.62, 0.48, 0.18, 0.07, 0.01, 108,  -6.2),
    "rap / spoken":      (0.80, 0.66, 0.44, 0.13, 0.28, 0.00,  96,  -6.8),
    "ambient / study":   (0.30, 0.19, 0.24, 0.71, 0.03, 0.86,  84, -18.0),
    "high-bpm dance":    (0.79, 0.90, 0.66, 0.03, 0.06, 0.35, 148,  -4.1),
}
WORLD_SPREAD = (0.10, 0.11, 0.16, 0.14, 0.04, 0.15, 11.0, 2.4)
BOUNDED = (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 40.0, -60.0)
UPPER = (1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 210.0, 0.0)
FEATS = ["danceability", "energy", "valence", "acousticness",
         "speechiness", "instrumentalness", "tempo", "loudness"]

# The true coefficients the analysis is meant to recover.
TRUE = {"intercept": -1.35, "affinity": 1.50, "arousal": 0.35, "valence_intensity": 0.25}

ADJ = ["Velvet", "Paper", "Northern", "Slow", "Glass", "Amber", "Quiet", "Neon",
       "Hollow", "Salt", "Copper", "Wild", "Blue", "Midnight", "Pale", "Iron",
       "Soft", "Distant", "Golden", "Static", "Lonesome", "Electric"]
NOUN = ["Harbour", "Machines", "Cathedral", "Weather", "Orchard", "Signal",
        "Lantern", "Avenue", "Ceiling", "Rivers", "Cassette", "Garden",
        "Motel", "Telegraph", "Season", "Kingdom", "Static", "Foxes"]
TITLE_A = ["Nothing", "Everything", "Some Nights", "Half", "Slow Dancing",
           "Radio", "The Long Way", "Cold Open", "Second", "Almost", "Backseat",
           "Ninety Miles", "All the Same", "Blue Hour", "Faultline", "Homework"]
TITLE_B = ["Again", "in June", "for Free", "at the End", "Without You",
           "Anyway", "Tonight", "in Reverse", "Out Loud", "by Morning",
           "Forever", "Downhill", "on Repeat", "in Colour", ""]


def _names(rng: np.random.Generator, n: int) -> tuple[list[str], list[str]]:
    artists = [f"{ADJ[i % len(ADJ)]} {NOUN[(i * 7) % len(NOUN)]}"
               for i in rng.permutation(len(ADJ) * len(NOUN))[:max(60, n // 12)]]
    a = rng.choice(artists, n)
    t = [f"{TITLE_A[i]} {TITLE_B[j]}".strip()
         for i, j in zip(rng.integers(0, len(TITLE_A), n),
                         rng.integers(0, len(TITLE_B), n))]
    # Disambiguate collisions so track identity stays 1:1 with a name.
    seen: dict[str, int] = {}
    out = []
    for artist, title in zip(a, t):
        key = f"{artist}|{title}"
        seen[key] = seen.get(key, 0) + 1
        out.append(title if seen[key] == 1 else f"{title} (v{seen[key]})")
    return list(a), out


def build_tracks(rng: np.random.Generator, birth_year: int) -> pd.DataFrame:
    world_names = list(WORLDS)
    # Taste drifts: world mix is re-weighted per year rather than fixed.
    world_idx = rng.integers(0, len(world_names), N_TRACKS)

    centres = np.array([WORLDS[world_names[i]] for i in world_idx])
    spread = np.array(WORLD_SPREAD)
    vals = rng.normal(centres, spread)
    vals = np.clip(vals, BOUNDED, UPPER)

    df = pd.DataFrame(vals, columns=FEATS)
    df["true_world"] = [world_names[i] for i in world_idx]

    # Entry dates: library growth accelerates through the teens, then plateaus.
    span_days = (END - START).days
    u = rng.beta(1.7, 1.5, N_TRACKS)          # front-loaded but long-tailed
    df["entered"] = START + pd.to_timedelta((u * span_days).astype(int), unit="D")

    artists, titles = _names(rng, N_TRACKS)
    df["artist"], df["name"] = artists, titles
    df["track_id"] = [f"sim{i:05d}" for i in range(N_TRACKS)]
    df["duration_ms"] = rng.normal(215_000, 46_000, N_TRACKS).clip(80_000, 480_000).astype(int)
    df["popularity"] = rng.integers(4, 92, N_TRACKS)
    df["release_date"] = (df["entered"] - pd.to_timedelta(
        rng.integers(0, 2600, N_TRACKS), unit="D")).dt.strftime("%Y-%m-%d")

    # Affinity: idiosyncratic, deliberately independent of acoustics.
    df["affinity"] = rng.normal(0, 1, N_TRACKS)

    # How tightly a track is bound to one period. Lognormal: most tracks live in
    # a season, a few become permanent furniture.
    df["burst_sd_days"] = np.exp(rng.normal(np.log(70), 0.85, N_TRACKS)).clip(9, 1400)

    df["age_at_entry"] = (df["entered"].dt.year - birth_year
                          + df["entered"].dt.dayofyear / 365.25)
    return df


def assign_returners(df: pd.DataFrame, rng: np.random.Generator) -> pd.DataFrame:
    z = lambda s: (s - s.mean()) / s.std()
    arousal = 0.6 * df["energy"] + 0.4 * ((df["loudness"] + 60) / 60).clip(0, 1)
    vint = (df["valence"] - 0.5).abs() * 2

    logit = (TRUE["intercept"]
             + TRUE["affinity"] * df["affinity"]
             + TRUE["arousal"] * z(arousal)
             + TRUE["valence_intensity"] * z(vint))
    p = 1 / (1 + np.exp(-logit))
    df["true_returner"] = rng.random(len(df)) < p

    # The revival lands 1.2-6 years after the original burst.
    df["revival_lag_days"] = rng.integers(440, 2200, len(df))
    return df


def build_streams(df: pd.DataFrame, rng: np.random.Generator) -> pd.DataFrame:
    """Plays as a burst around entry, plus a revival burst for returners."""
    rows = []
    for t in df.itertuples():
        # Total plays: affinity-driven, heavy-tailed. The intercept is set so a
        # 13-year history lands in the tens of thousands of streams, which is
        # the order of magnitude a real export comes in at.
        mu = np.exp(3.0 + 0.85 * t.affinity)
        n = int(np.clip(rng.poisson(mu), 1, 900))

        offs = rng.normal(t.burst_sd_days * 0.55, t.burst_sd_days, n)
        offs = np.abs(offs)

        if t.true_returner:
            # A quarter to a half of a returner's plays arrive in the revival.
            k = int(n * rng.uniform(0.22, 0.5))
            if k:
                rev = rng.normal(t.revival_lag_days, 95, k)
                offs = np.concatenate([offs[:n - k], np.abs(rev)])

        when = t.entered + pd.to_timedelta(offs.astype(int), unit="D")
        when = when[when <= END]
        if not len(when):
            when = pd.DatetimeIndex([t.entered])

        # Completion: liked tracks get played through, others get skipped.
        frac = np.clip(rng.beta(2.2 + 1.6 * max(t.affinity, -1.2), 1.05,
                                len(when)), 0.02, 1.0)
        rows.append(pd.DataFrame({
            "played_at": when,
            "track_id": t.track_id,
            "ms_played": (frac * t.duration_ms).astype(int),
        }))

    return pd.concat(rows, ignore_index=True).sort_values("played_at")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--birth-year", type=int, default=2005)
    args = ap.parse_args()

    rng = np.random.default_rng(args.seed)
    DATA.mkdir(parents=True, exist_ok=True)

    tracks = assign_returners(build_tracks(rng, args.birth_year), rng)
    streams = build_streams(tracks, rng)

    tracks["simulated"] = True
    tracks.drop(columns=["revival_lag_days"]).to_csv(DATA / "tracks.csv", index=False)
    streams.to_csv(DATA / "streams.csv", index=False)

    span = (streams.played_at.max() - streams.played_at.min()).days
    source = {
        "ingest": "SIMULATED",
        "simulated": True,
        "seed": args.seed,
        "birth_year": args.birth_year,
        "streams": int(len(streams)),
        "unique_tracks": int(len(tracks)),
        "first_play": str(streams.played_at.min().date()),
        "last_play": str(streams.played_at.max().date()),
        "span_days": int(span),
        "span_years": round(span / 365.25, 2),
        "audio_features": "simulated",
        "audio_feature_columns": FEATS,
        "audio_feature_coverage": 1.0,
        "history_depth": "full_export",
        "true_parameters": TRUE,
        "true_worlds": list(WORLDS),
        "warning": ("Synthetic data. Every finding computed from it describes "
                    "the simulator, not a person. It exists so the pipeline can "
                    "be run and checked without access to a private account."),
    }
    (DATA / "source.json").write_text(json.dumps(source, indent=2))

    print(f"tracks       : {len(tracks):,}  ({tracks.true_returner.mean():.1%} true returners)")
    print(f"streams      : {len(streams):,}")
    print(f"span         : {source['first_play']} -> {source['last_play']}"
          f"  ({source['span_years']} years)")
    print(f"written      : {DATA}/tracks.csv, {DATA}/streams.csv")
    print("\nNext: python memory-lane/run_memory_lane.py")


if __name__ == "__main__":
    main()
